import {
  Settings,
  Landmark,
  Layers,
  Link as LinkIcon,
  Network,
  Sliders,
  Grid,
  Shield,
  Users,
  Wallet,
  UserSquare,
  Clock,
  Calendar,
  FileText,
  Building2,
  Briefcase,
  Inbox,
  Percent,
  FileSpreadsheet,
  BarChart,
  ShoppingBag,
  TrendingUp,
  Calculator,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  settings: Settings,
  landmark: Landmark,
  layers: Layers,
  link: LinkIcon,
  network: Network,
  sliders: Sliders,
  grid: Grid,
  shield: Shield,
  users: Users,
  wallet: Wallet,
  'user-square': UserSquare,
  clock: Clock,
  calendar: Calendar,
  'file-text': FileText,
  'building-2': Building2,
  briefcase: Briefcase,
  inbox: Inbox,
  percent: Percent,
  'file-spreadsheet': FileSpreadsheet,
  'bar-chart': BarChart,
  'shopping-bag': ShoppingBag,
  'trending-up': TrendingUp,
  calculator: Calculator,
};
